//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGSACH
    {
        public BANGSACH()
        {
            this.CHITIET_HOADON = new HashSet<CHITIET_HOADON>();
        }
    
        public int MASACH { get; set; }
        public string TENSACH { get; set; }
        public Nullable<int> GIABAN { get; set; }
        public string NOIDUNG { get; set; }
        public string ANHBIA { get; set; }
        public Nullable<int> NAMXUATBAN { get; set; }
        public Nullable<int> MALOAI { get; set; }
        public Nullable<int> MANXB { get; set; }
    
        public virtual ICollection<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        public virtual LOAISACH LOAISACH { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
    }
}
