//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public HOADON()
        {
            this.CHITIET_HOADON = new HashSet<CHITIET_HOADON>();
        }
    
        public int MAHOADON { get; set; }
        public Nullable<int> MAKHACHHANG { get; set; }
        public Nullable<int> MANHANVIEN { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<int> TONGTIEN { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> MATINHTRANG { get; set; }
    
        public virtual ICollection<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual TINHTRANG TINHTRANG { get; set; }
    }
}
