//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int MANHANVIEN { get; set; }
        public string TENNHANVIEN { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<int> MAVAITRO { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual VAITRO VAITRO { get; set; }
    }
}
