//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAXUATBAN
    {
        public NHAXUATBAN()
        {
            this.BANGSACHes = new HashSet<BANGSACH>();
        }
    
        public int MANXB { get; set; }
        public string TENNXB { get; set; }
        public string DIACHI { get; set; }
    
        public virtual ICollection<BANGSACH> BANGSACHes { get; set; }
    }
}
