//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanSach
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_SACHEntities : DbContext
    {
        public QL_SACHEntities()
            : base("name=QL_SACHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BANGSACH> BANGSACHes { get; set; }
        public DbSet<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<LOAISACH> LOAISACHes { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<NHAXUATBAN> NHAXUATBANs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TINHTRANG> TINHTRANGs { get; set; }
        public DbSet<VAITRO> VAITROes { get; set; }
    }
}
