//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINHTRANG
    {
        public TINHTRANG()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int MATINHTRANG { get; set; }
        public string TINHTRANGHOADON { get; set; }
    
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
